name: rohd_vf
description: The ROHD Verification Framework, a verification framework built upon ROHD for building testbenches.
version: 0.1.0
homepage: https://www.github.com/intel/rohd-vf

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  rohd: ^0.1.0
  logging: ^1.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.3
